project_id = "hyglnwkdthdewhqeqqss"

[functions.claude-generate]
verify_jwt = false

[functions.shopify-create-landing]
verify_jwt = false

[functions.shopify-upsert-mapping]
verify_jwt = false

[functions.shopify-get-mapping]
verify_jwt = false