// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Types disabled to avoid missing generated types during setup

const SUPABASE_URL = "https://hyglnwkdthdewhqeqqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Z2xud2tkdGhkZXdocWVxcXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjYyMzQsImV4cCI6MjA3MDIwMjIzNH0.uOfeGxOk9oXul9u_EbnArCaIDnPJ-UBquFQeb9Z9m2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});